#!/usr/bin/env bash

vcfg_cmd_help() {
  echo -e "${CYAN}vcfg${NC} - Vim Configuration Manager"
  echo ""
  echo -e "${WHITE}USAGE:${NC}"
  echo "  vcfg <command> [arguments]"
  echo ""
  echo -e "${WHITE}COMMANDS:${NC}"
  echo -e "  ${GREEN}add${NC} <plugin>        Add a new plugin (e.g., 'tpope/vim-fugitive')"
  echo -e "  ${GREEN}remove${NC} <plugin>     Remove a plugin completely"
  echo -e "  ${GREEN}disable${NC} <plugin>    Disable a plugin (comment it out)"
  echo -e "  ${GREEN}enable${NC} <plugin>     Enable a disabled plugin"
  echo -e "  ${GREEN}list${NC}                List all installed plugins"
  echo -e "  ${GREEN}search${NC} <query>      Search for plugins on GitHub"
  echo -e "  ${GREEN}update${NC}              Update all plugins"
  echo -e "  ${GREEN}clean${NC}               Remove unused plugins"
  echo -e "  ${GREEN}info${NC} <plugin>       Show plugin information"
  echo ""
  echo -e "${WHITE}OPTIONS:${NC}"
  echo -e "  ${GREEN}--version|-v${NC}        Show version information"
  echo -e "  ${GREEN}--help|-h${NC}           Show this help message"
  echo ""
  echo -e "${WHITE}EXAMPLES:${NC}"
  echo "  vcfg add preservim/nerdtree"
  echo "  vcfg remove vim-airline"
  echo "  vcfg disable coc.nvim"
  echo "  vcfg search fuzzy"
  echo "  vcfg list"
  echo ""
  echo -e "${WHITE}PLUGIN FORMAT:${NC}"
  echo -e "  Full format: ${CYAN}username/repository${NC}"
  echo -e "  Short format: ${CYAN}plugin-name${NC} (will search for exact match)"
  echo ""
}
